Moved print IR to utils submodule; added submodule for region_t bindings
ampersand-projects/tilt pull request #47
Opened 2023-07-06 18:40 UTC by jasperrxzhu

To work around the lack of `char*` support by pybind11, I created a new `PyReg` class that acts as a Python wrapper for `region_t` structures. Previously with the C++ API, users had to allocate their own arrays for timestamps and data, and then invoke `init_region` to initialize a `region_t` structure properly. In this case, I have not created bindings for `ival_t` or `char*` and a Python user is not responsible for allocating the above arrays. Instead, the user specifies the desired size (in terms of number of elements in the stream) and a schema for the data stream, and the `PyReg` object takes care of memory management with respect to timestamps and data. 

To write data to `region_t` structure underlying a `PyReg` object, I've added a `write_data` binding. This is essentially the equivalent of using fetch and then dereferencing to write data to a `region_t` object. I make use of pybind11's Python C++ interface (https://pybind11.readthedocs.io/en/stable/advanced/pycpp/index.html) and the `PyReg` object's schema to make sure that the Python value that a user wants to write to the stream is converted the appropriate underlying C++ data format. 

Bindings for all other `region_t` related functions are created as methods for the `PyReg` class. 

I have a `Cvtr` class because I initially expected to need more utility functions, but these can just be moved into the DataType class if you'd like (i.e. in tilt/base/type.h).

2023-07-19 15:51 UTC, jasperrxzhu commented
PR is still incomplete.

Currently looking for an alternative to the non-const reference issue being raised in `python/region/src/bindings.cpp:19`. There is also a bug that does not allow me to compile/execute multiple TiLT queries sequentially within the same python file.

2023-08-06 22:08 UTC, anandj91 requested changes

2023-08-06 22:08 UTC, anandj91 commented on include/tilt/pass/codegen/llvmgen.h
> +    {}
Why do we need two ctors? there is another one defined that accepts LLVMContext as argument at line 64.

2023-08-06 22:08 UTC, anandj91 commented on python/src/bindings/ir.cpp
> +        .value("_or", MathOp::OR);
We need to keep the naming style consistent. Can we make all the function binding to start with "_" ? Or is there a better way to make it consistent. I had similar conflict issue with C++ APIs as well. That is why I started using this convention.

2023-08-06 22:08 UTC, anandj91 commented on src/pass/codegen/llvmgen.cpp
> +    total_bytes = total_bytes / 8;
Can you use llsizeof() for this? You can either modify llsizeof to return an integer or convert the ConstantInt llvm value back to an integer.

2023-08-06 22:08 UTC, anandj91 commented on src/pass/codegen/llvmgen.cpp
> +StructPaddingInfo LLVMGen::build_struct_padding(const DataType& dtype)
Can we name StructPaddingInfo to just PaddingInfo? It looks like you are creating this object even if the datatype is not a struct.

2023-08-06 22:08 UTC, anandj91 commented on python/include/pyreg.h
> +                           char* raw_data_ptr);
do we need these helper functions to be part of the class? You can define them only in the pyreg.cpp file

2023-08-06 22:08 UTC, anandj91 commented on python/include/pyreg.h
> +    void write_btype_data_to_ptr(py::object payload, char* raw_data_ptr);
same for this.

2023-08-06 22:08 UTC, anandj91 commented on python/include/pyreg.h
> +    void write_data(py::object payload, ts_t t, idx_t i);
we also need a function to read data from the region. We can add that later.

2023-08-22 16:27 UTC, anandj91 approved these changes

2023-08-22 16:28 UTC, merged